name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail, wrath, classic, cata]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: BigWigsMods/packager@master
      with:
        args: -p 914482 -a kGr09M6y -g ${{matrix.type}}
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
